name: alex_transit
description: Alexandria-focused transit navigation app (sample implementation).
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_map_location_marker: ^10.1.0
  location: ^8.0.1
  flutter_polyline_points: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_map_tile_caching: ^10.1.1

  latlong2: ^0.9.1
  http: ^1.5.0
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.4.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations.json
    - assets/stations.json
    - assets/lines.json
    - .env
